### ISSUE TITLE
can not open it

### ISSUE THREAD

**Issue by xxxxxxH** [thesandipv/pointer_replacer#7]
can not open it with MI 8SE sos!
![企业微信截图_16181931548073](https://user-images.githubusercontent.com/20770054/114331530-ce07dc80-9b76-11eb-8b69-f0784083388a.png)

**Comment by thesandipv** [comment]
Please explain in detail.

**Comment by xxxxxxH** [comment]
I cloned your project directly, and it was stuck on the loading interface.

**Comment by thesandipv** [comment]
Ok. You need to create separate firebase project.
